sudo: required
dist: bionic
language: python
cache: pip
python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - python -m pip install --upgrade pip setuptools wheel
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt

install:
  - check-manifest
  - python setup.py sdist bdist_wheel
  - twine check dist/*

script:
#  - pytest --cov=. tests/
  - pytest --mypy --black tests/
  - pytest --black -m black src/

#after_success:
#  - codecov -F $TEST
